using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MouseHandler : MonoBehaviour
{

    //14/4/16: Variables moved from the Player Input Handler:
    private TargetFrenzy Inputs; // Reference to the Inputs script generated by the input action asset
    private Vector3 mousePos; //Stores the screen space mouse position    
    private Vector3 mouseWorldPos; // Stores the world space mouse position
    private GameObject currentTarget; //To store the target the mouse is current hovering over --14/4/24: This has now been moved to the new Mouse Handler script, as its more relevant to that script than the input handler
    
    public GameObject CurrentTarget //Property field so the Player Input script can access the 'current target'
    {
        get { return currentTarget;}
     }

    void Start()
    {
        Inputs = new TargetFrenzy(); // Creates a new instance of inputs. Next, enable to map which has the action
        Inputs.Player.Enable(); //Enable the input to be able to read the mouse position
    }

    //Update is called once per frame
    private void Update()
    {
        mousePos = Inputs.Player.Look.ReadValue<Vector2>(); //Reads and updates the mouse position on screen (In screen space)
        mousePos.z = Camera.main.nearClipPlane; //Set the z coordinate to the camera's near clip - this will keep it in the visible area
        mouseWorldPos = Camera.main.ScreenToWorldPoint(mousePos); //Converts the screen space coordinates to world space (provides xyz coordinates

        //Raycast code taken from the target detection script for testing - Placing the raycast code here means each target gameobject wont need to have the "target detection"
        //script attached to it

        //Fire a raycast that will detect the targets by tag
        RaycastHit2D hit = Physics2D.Raycast(new Vector2(mouseWorldPos.x, mouseWorldPos.y), Vector2.zero, 0);
        Debug.DrawRay(mouseWorldPos, Vector2.up * 0.1f, Color.red, 10f);

        if (hit)
        {
            currentTarget = hit.collider.gameObject; //Debug.Log($"Hovering over: {currentTarget.name}"); 
        }
        else
        {
            currentTarget = null;  //Debug.Log("Nothing detected"); //for debugging
        }
    }
}
