using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.TextCore.Text;
using UnityEngine.UI;

public class MouseInput : MonoBehaviour
{
    //Variables
    private TargetFrenzy Inputs; // Reference to the Inputs script generated by the input action asset
    private Vector3 mousePos; //Stores the screen space mouse position    
    public static Vector3 mouseWorldPos; // Stores the world space mouse position

    //Exposed part to assign the gameobject this script should compare tags (Will need to be revised when the other targets are implemented - using an array)

    //[SerializeField] List<GameObject> targetObjects = new List<GameObject>();

    private GameObject currentTarget; //To store the target the mouse is current hovering over

    private int maxMisses = 3; //Max amount of possible clicks the player has before resulting in a game over
    private int missCount = 0; //Variable that will track the player's misses 

    //Actions
    public static event Action OnPlayerMissUI;
    public static event Action OnPlayerReload;



    private void Start()
    {
        Inputs = new TargetFrenzy(); // Creates a new instance of inputs. Next, enable to map which has the action
        Inputs.Player.Enable(); //Enable the input to be able to read the mouse position
    }

    private void Update()
    {
        mousePos = Inputs.Player.Look.ReadValue<Vector2>(); //Reads and updates the mouse position on screen (In screen space)
        mousePos.z = Camera.main.nearClipPlane; //Set the z coordinate to the camera's near clip - this will keep it in the visible area
        mouseWorldPos = Camera.main.ScreenToWorldPoint(mousePos); //Converts the screen space coordinates to world space (provides xyz coordinates)

        //Debug.Log(mouseWorldPos); //Displays the current mouse position in the console


        //Raycast code taken from the target detection script for testing - Placing the raycast code here means each target gameobject wont need to have the "target detection"
        //script attached to it

        //Fire a raycast that will detect the targets by tag
        RaycastHit2D hit = Physics2D.Raycast(new Vector2(mouseWorldPos.x, mouseWorldPos.y), Vector2.zero, 0);
        Debug.DrawRay(MouseInput.mouseWorldPos, Vector2.up * 0.1f, Color.red, 10f);

        if (hit)
        {
            currentTarget = hit.collider.gameObject;
           //Debug.Log($"Hovering over: {currentTarget.name}"); 

        }
        else
        {
            currentTarget = null;
            //Debug.Log("Nothing detected"); //for debugging
        }
    }


    //Method for shooting / firing - using Unity Events as the notification behaviour 
    public void OnFire(InputAction.CallbackContext context)
    {
        if (context.performed) //Check if the action has been performed / completed
        {
            if (currentTarget != null) //If the mouse IS currently hovering over a target, destroy the current target
            {
                TargetClass Target = currentTarget.GetComponent<TargetClass>();
                
                if (Target != null) //Change the If statement to a switch statement (Due to the multiple targets)
                {
                    Target.OnHit();
                }

                Destroy(currentTarget);
            }
            else
            {
                Debug.Log("You have clicked on nothing");

                //Invoke Action
                OnPlayerMissUI?.Invoke();
                PlayerMiss();
                
            }
        }
    }

    public void OnReload(InputAction.CallbackContext context) //Reload is mapped to the "R" key as of now
    {
        //For handling reloading
        if (!context.performed) //Checks if the R key was NOT PRESSED (performed)
        {
            return;
        }
        else
        {
            //Code here - Invoke any actions here!
            OnPlayerReload?.Invoke();
            Debug.Log("Reload performed");
            
            
        }
    }

    private void PlayerMiss() //Method responsible for the player's misses
    {
        missCount++;
        Debug.Log("Missed Counts: " + missCount);

        if (missCount > maxMisses)
        {
            //The player input map needs to be disable here, as the game still registers inputs and the "OnFire" method is still called

            //Inputs.Player.Disable(); // This disables the player action map! 

            Debug.Log("Game Over");

            //GameManager.Instance.GameOver();

            return;
        }
    }
}
